WITH seed_puzzles (
  id,
  source,
  format,
  game_state,
  player_side,
  question_type,
  correct_action,
  wrong_actions,
  explanation,
  difficulty,
  tags,
  status,
  approved_at
) AS (
  VALUES
  (
    '11111111-1111-4111-8111-111111111111'::uuid,
    'replay',
    'reg-h',
    '{"turn":5,"weather":null,"terrain":"Electric Terrain","pseudoWeather":[],"p1":{"sideConditions":["Tailwind"],"active":[{"species":"Miraidon","level":50,"currentHp":167,"maxHp":167,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Electro Drift","Draco Meteor","Protect","Volt Switch"],"item":"Choice Specs","ability":"Hadron Engine","stats":{"spe":205,"atk":94,"spa":205,"def":120,"spd":135}},{"species":"Flutter Mane","level":50,"currentHp":121,"maxHp":131,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Moonblast","Shadow Ball","Protect","Icy Wind"],"item":"Focus Sash","ability":"Protosynthesis","stats":{"spe":205,"atk":67,"spa":205,"def":75,"spd":155}}],"bench":[]},"p2":{"sideConditions":[],"active":[{"species":"Iron Hands","level":50,"currentHp":227,"maxHp":227,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Fake Out","Drain Punch","Wild Charge","Protect"],"item":"Assault Vest","ability":"Quark Drive","stats":{"spe":107,"atk":211,"spa":63,"def":128,"spd":100}},{"species":"Rillaboom","level":50,"currentHp":108,"maxHp":197,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Grassy Glide","Wood Hammer","Fake Out","Protect"],"item":"Miracle Seed","ability":"Grassy Surge","stats":{"spe":137,"atk":194,"spa":72,"def":110,"spd":90}}],"bench":[]}}'::jsonb,
    'p1',
    'speed_check',
    '{"type":"move","move":"Electro Drift","target":"p2a"}'::jsonb,
    '[{"type":"move","move":"Moonblast","target":"p2a"},{"type":"move","move":"Draco Meteor","target":"p2b"},{"type":"switch","value":"bench-slot-1"}]'::jsonb,
    '{"templateType":"speed_check","fields":{"winner":"Miraidon","reason":"Miraidon outspeeds Iron Hands even before Tailwind and safely acts first."}}'::jsonb,
    1,
    ARRAY['speed_check','terrain','miraidon'],
    'approved',
    now()
  ),
  (
    '22222222-2222-4222-8222-222222222222'::uuid,
    'replay',
    'reg-h',
    '{"turn":7,"weather":null,"terrain":null,"pseudoWeather":[],"p1":{"sideConditions":[],"active":[{"species":"Urshifu-Rapid-Strike","level":50,"currentHp":175,"maxHp":175,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Surging Strikes","Close Combat","Aqua Jet","Protect"],"item":"Choice Band","ability":"Unseen Fist","stats":{"spe":149,"atk":200,"spa":74,"def":120,"spd":80}},{"species":"Amoonguss","level":50,"currentHp":221,"maxHp":221,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Spore","Rage Powder","Pollen Puff","Protect"],"item":"Rocky Helmet","ability":"Regenerator","stats":{"spe":31,"atk":94,"spa":105,"def":134,"spd":100}}],"bench":[]},"p2":{"sideConditions":[],"active":[{"species":"Dondozo","level":50,"currentHp":285,"maxHp":285,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Wave Crash","Order Up","Protect","Earthquake"],"item":"Leftovers","ability":"Unaware","stats":{"spe":55,"atk":167,"spa":76,"def":135,"spd":85}},{"species":"Tatsugiri","level":50,"currentHp":131,"maxHp":131,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Draco Meteor","Muddy Water","Protect","Icy Wind"],"item":"Choice Scarf","ability":"Commander","stats":{"spe":147,"atk":63,"spa":170,"def":80,"spd":115}}],"bench":[]}}'::jsonb,
    'p1',
    'ko_threshold',
    '{"type":"move","move":"Surging Strikes","target":"p2a"}'::jsonb,
    '[{"type":"move","move":"Close Combat","target":"p2a"},{"type":"move","move":"Aqua Jet","target":"p2a"},{"type":"move","move":"Spore","target":"p2a"}]'::jsonb,
    '{"templateType":"ko_threshold","fields":{"winner":"Surging Strikes","reason":"Choice Band Surging Strikes is the deterministic damage line into Dondozo."}}'::jsonb,
    2,
    ARRAY['ko_threshold','urshifu','dondozo'],
    'approved',
    now()
  ),
  (
    '33333333-3333-4333-8333-333333333333'::uuid,
    'replay',
    'reg-h',
    '{"turn":4,"weather":null,"terrain":null,"pseudoWeather":["Trick Room"],"p1":{"sideConditions":[],"active":[{"species":"Porygon2","level":50,"currentHp":177,"maxHp":177,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Trick Room","Ice Beam","Recover","Thunderbolt"],"item":"Eviolite","ability":"Download","stats":{"spe":58,"atk":76,"spa":125,"def":135,"spd":135}},{"species":"Amoonguss","level":50,"currentHp":221,"maxHp":221,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Spore","Rage Powder","Pollen Puff","Protect"],"item":"Sitrus Berry","ability":"Regenerator","stats":{"spe":31,"atk":94,"spa":105,"def":134,"spd":100}}],"bench":[]},"p2":{"sideConditions":[],"active":[{"species":"Tornadus","level":50,"currentHp":167,"maxHp":167,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Bleakwind Storm","Tailwind","Taunt","Protect"],"item":"Choice Scarf","ability":"Prankster","stats":{"spe":179,"atk":105,"spa":145,"def":90,"spd":100}},{"species":"Landorus-Therian","level":50,"currentHp":185,"maxHp":185,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Stomping Tantrum","Rock Slide","U-turn","Protect"],"item":"Clear Amulet","ability":"Intimidate","stats":{"spe":143,"atk":216,"spa":105,"def":110,"spd":100}}],"bench":[]}}'::jsonb,
    'p1',
    'field_interaction',
    '{"type":"move","move":"Spore","target":"p2a"}'::jsonb,
    '[{"type":"move","move":"Ice Beam","target":"p2b"},{"type":"move","move":"Tailwind","target":"p2a"},{"type":"switch","value":"bench-slot-1"}]'::jsonb,
    '{"templateType":"field_interaction","fields":{"winner":"Amoonguss","reason":"Under Trick Room the slowest active Pokemon acts first, so Amoonguss moves before Choice Scarf Tornadus."}}'::jsonb,
    2,
    ARRAY['field_interaction','trick_room','speed_check'],
    'approved',
    now()
  ),
  (
    '44444444-4444-4444-8444-444444444444'::uuid,
    'replay',
    'reg-h',
    '{"turn":6,"weather":"RainDance","terrain":null,"pseudoWeather":[],"p1":{"sideConditions":[],"active":[{"species":"Archaludon","level":50,"currentHp":197,"maxHp":197,"status":null,"statBoosts":{"atk":0,"def":0,"spa":1,"spd":0,"spe":0},"moves":["Electro Shot","Draco Meteor","Body Press","Protect"],"item":"Assault Vest","ability":"Stamina","stats":{"spe":105,"atk":112,"spa":177,"def":165,"spd":95}},{"species":"Pelipper","level":50,"currentHp":135,"maxHp":135,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Hurricane","Weather Ball","Tailwind","Protect"],"item":"Focus Sash","ability":"Drizzle","stats":{"spe":128,"atk":63,"spa":150,"def":120,"spd":90}}],"bench":[]},"p2":{"sideConditions":[],"active":[{"species":"Flutter Mane","level":50,"currentHp":131,"maxHp":131,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Moonblast","Shadow Ball","Protect","Icy Wind"],"item":"Booster Energy","ability":"Protosynthesis","stats":{"spe":205,"atk":67,"spa":205,"def":75,"spd":155}},{"species":"Incineroar","level":50,"currentHp":201,"maxHp":201,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Fake Out","Flare Blitz","Knock Off","Parting Shot"],"item":"Safety Goggles","ability":"Intimidate","stats":{"spe":91,"atk":183,"spa":90,"def":110,"spd":110}}],"bench":[]}}'::jsonb,
    'p1',
    'ko_threshold',
    '{"type":"move","move":"Electro Shot","target":"p2a"}'::jsonb,
    '[{"type":"move","move":"Draco Meteor","target":"p2b"},{"type":"move","move":"Body Press","target":"p2b"},{"type":"move","move":"Tailwind","target":"p1a"}]'::jsonb,
    '{"templateType":"ko_threshold","fields":{"winner":"Electro Shot","reason":"Rain lets Electro Shot fire immediately and the +1 special attack line targets Flutter Mane effectively."}}'::jsonb,
    3,
    ARRAY['ko_threshold','rain','archaludon'],
    'approved',
    now()
  ),
  (
    '55555555-5555-4555-8555-555555555555'::uuid,
    'replay',
    'reg-h',
    '{"turn":3,"weather":null,"terrain":"Grassy Terrain","pseudoWeather":[],"p1":{"sideConditions":[],"active":[{"species":"Rillaboom","level":50,"currentHp":197,"maxHp":197,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Fake Out","Grassy Glide","Wood Hammer","Protect"],"item":"Miracle Seed","ability":"Grassy Surge","stats":{"spe":137,"atk":194,"spa":72,"def":110,"spd":90}},{"species":"Kingambit","level":50,"currentHp":207,"maxHp":207,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Kowtow Cleave","Sucker Punch","Iron Head","Protect"],"item":"Black Glasses","ability":"Defiant","stats":{"spe":70,"atk":205,"spa":72,"def":140,"spd":105}}],"bench":[]},"p2":{"sideConditions":[],"active":[{"species":"Urshifu-Rapid-Strike","level":50,"currentHp":55,"maxHp":175,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Surging Strikes","Close Combat","Aqua Jet","Protect"],"item":"Focus Sash","ability":"Unseen Fist","stats":{"spe":149,"atk":200,"spa":74,"def":120,"spd":80}},{"species":"Farigiraf","level":50,"currentHp":192,"maxHp":192,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Trick Room","Psychic","Helping Hand","Protect"],"item":"Throat Spray","ability":"Armor Tail","stats":{"spe":80,"atk":90,"spa":178,"def":90,"spd":110}}],"bench":[]}}'::jsonb,
    'p1',
    'field_interaction',
    '{"type":"move","move":"Grassy Glide","target":"p2a"}'::jsonb,
    '[{"type":"move","move":"Fake Out","target":"p2b"},{"type":"move","move":"Sucker Punch","target":"p2a"},{"type":"move","move":"Wood Hammer","target":"p2b"}]'::jsonb,
    '{"templateType":"field_interaction","fields":{"winner":"Grassy Glide","reason":"Grassy Terrain gives Grassy Glide priority, letting Rillaboom pick off low HP Urshifu."}}'::jsonb,
    2,
    ARRAY['field_interaction','priority','grassy_terrain'],
    'approved',
    now()
  ),
  (
    '66666666-6666-4666-8666-666666666666'::uuid,
    'replay',
    'reg-h',
    '{"turn":8,"weather":null,"terrain":null,"pseudoWeather":[],"p1":{"sideConditions":[],"active":[{"species":"Gholdengo","level":50,"currentHp":163,"maxHp":163,"status":null,"statBoosts":{"atk":0,"def":0,"spa":2,"spd":0,"spe":0},"moves":["Make It Rain","Shadow Ball","Nasty Plot","Protect"],"item":"Life Orb","ability":"Good as Gold","stats":{"spe":136,"atk":72,"spa":203,"def":115,"spd":111}},{"species":"Incineroar","level":50,"currentHp":201,"maxHp":201,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Fake Out","Flare Blitz","Knock Off","Parting Shot"],"item":"Sitrus Berry","ability":"Intimidate","stats":{"spe":91,"atk":183,"spa":90,"def":110,"spd":110}}],"bench":[]},"p2":{"sideConditions":[],"active":[{"species":"Calyrex-Ice","level":50,"currentHp":207,"maxHp":207,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Glacial Lance","High Horsepower","Trick Room","Protect"],"item":"Clear Amulet","ability":"As One","stats":{"spe":70,"atk":238,"spa":105,"def":170,"spd":150}},{"species":"Amoonguss","level":50,"currentHp":221,"maxHp":221,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Spore","Rage Powder","Pollen Puff","Protect"],"item":"Rocky Helmet","ability":"Regenerator","stats":{"spe":31,"atk":94,"spa":105,"def":134,"spd":100}}],"bench":[]}}'::jsonb,
    'p1',
    'ko_threshold',
    '{"type":"move","move":"Make It Rain","target":"p2a"}'::jsonb,
    '[{"type":"move","move":"Shadow Ball","target":"p2b"},{"type":"move","move":"Fake Out","target":"p2a"},{"type":"move","move":"Parting Shot","target":"p2a"}]'::jsonb,
    '{"templateType":"ko_threshold","fields":{"winner":"Make It Rain","reason":"+2 Life Orb Make It Rain is the spread damage line that pressures Calyrex-Ice immediately."}}'::jsonb,
    3,
    ARRAY['ko_threshold','gholdengo','spread_move'],
    'approved',
    now()
  ),
  (
    '77777777-7777-4777-8777-777777777777'::uuid,
    'replay',
    'reg-h',
    '{"turn":2,"weather":null,"terrain":null,"pseudoWeather":[],"p1":{"sideConditions":[],"active":[{"species":"Whimsicott","level":50,"currentHp":135,"maxHp":135,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Tailwind","Moonblast","Encore","Protect"],"item":"Focus Sash","ability":"Prankster","stats":{"spe":184,"atk":77,"spa":141,"def":105,"spd":95}},{"species":"Chi-Yu","level":50,"currentHp":131,"maxHp":131,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Heat Wave","Dark Pulse","Overheat","Protect"],"item":"Choice Specs","ability":"Beads of Ruin","stats":{"spe":167,"atk":76,"spa":205,"def":100,"spd":140}}],"bench":[]},"p2":{"sideConditions":[],"active":[{"species":"Flutter Mane","level":50,"currentHp":131,"maxHp":131,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Moonblast","Shadow Ball","Protect","Icy Wind"],"item":"Booster Energy","ability":"Protosynthesis","stats":{"spe":205,"atk":67,"spa":205,"def":75,"spd":155}},{"species":"Ogerpon-Wellspring","level":50,"currentHp":187,"maxHp":187,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Ivy Cudgel","Horn Leech","Follow Me","Spiky Shield"],"item":"Wellspring Mask","ability":"Water Absorb","stats":{"spe":178,"atk":189,"spa":80,"def":104,"spd":116}}],"bench":[]}}'::jsonb,
    'p1',
    'speed_check',
    '{"type":"move","move":"Tailwind","target":"p1a"}'::jsonb,
    '[{"type":"move","move":"Heat Wave","target":"p2a"},{"type":"move","move":"Dark Pulse","target":"p2a"},{"type":"move","move":"Moonblast","target":"p2b"}]'::jsonb,
    '{"templateType":"speed_check","fields":{"winner":"Tailwind","reason":"Prankster Tailwind gives immediate priority speed control before the opponent can attack."}}'::jsonb,
    1,
    ARRAY['speed_check','tailwind','priority'],
    'approved',
    now()
  ),
  (
    '88888888-8888-4888-8888-888888888888'::uuid,
    'replay',
    'reg-h',
    '{"turn":9,"weather":"Sun","terrain":null,"pseudoWeather":[],"p1":{"sideConditions":[],"active":[{"species":"Walking Wake","level":50,"currentHp":173,"maxHp":173,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Hydro Steam","Draco Meteor","Flamethrower","Protect"],"item":"Booster Energy","ability":"Protosynthesis","stats":{"spe":177,"atk":91,"spa":194,"def":105,"spd":103}},{"species":"Torkoal","level":50,"currentHp":177,"maxHp":177,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Eruption","Heat Wave","Earth Power","Protect"],"item":"Charcoal","ability":"Drought","stats":{"spe":31,"atk":105,"spa":150,"def":160,"spd":90}}],"bench":[]},"p2":{"sideConditions":[],"active":[{"species":"Landorus-Therian","level":50,"currentHp":90,"maxHp":185,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Stomping Tantrum","Rock Slide","U-turn","Protect"],"item":"Assault Vest","ability":"Intimidate","stats":{"spe":143,"atk":216,"spa":105,"def":110,"spd":100}},{"species":"Rillaboom","level":50,"currentHp":197,"maxHp":197,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Fake Out","Grassy Glide","Wood Hammer","Protect"],"item":"Miracle Seed","ability":"Grassy Surge","stats":{"spe":137,"atk":194,"spa":72,"def":110,"spd":90}}],"bench":[]}}'::jsonb,
    'p1',
    'ko_threshold',
    '{"type":"move","move":"Hydro Steam","target":"p2a"}'::jsonb,
    '[{"type":"move","move":"Draco Meteor","target":"p2b"},{"type":"move","move":"Eruption","target":"p2b"},{"type":"move","move":"Protect","target":"p1a"}]'::jsonb,
    '{"templateType":"ko_threshold","fields":{"winner":"Hydro Steam","reason":"Hydro Steam remains empowered in sun and targets Landorus-Therian for the clean KO line."}}'::jsonb,
    2,
    ARRAY['ko_threshold','sun','walking_wake'],
    'approved',
    now()
  ),
  (
    '99999999-9999-4999-8999-999999999999'::uuid,
    'replay',
    'reg-h',
    '{"turn":6,"weather":null,"terrain":null,"pseudoWeather":["Trick Room"],"p1":{"sideConditions":[],"active":[{"species":"Calyrex-Ice","level":50,"currentHp":207,"maxHp":207,"status":null,"statBoosts":{"atk":1,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Glacial Lance","High Horsepower","Trick Room","Protect"],"item":"Clear Amulet","ability":"As One","stats":{"spe":70,"atk":238,"spa":105,"def":170,"spd":150}},{"species":"Indeedee-F","level":50,"currentHp":177,"maxHp":177,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Follow Me","Psychic","Helping Hand","Protect"],"item":"Psychic Seed","ability":"Psychic Surge","stats":{"spe":105,"atk":76,"spa":115,"def":120,"spd":150}}],"bench":[]},"p2":{"sideConditions":[],"active":[{"species":"Dragonite","level":50,"currentHp":185,"maxHp":185,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Extreme Speed","Stomping Tantrum","Haze","Protect"],"item":"Choice Band","ability":"Inner Focus","stats":{"spe":132,"atk":204,"spa":105,"def":115,"spd":120}},{"species":"Incineroar","level":50,"currentHp":201,"maxHp":201,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Fake Out","Flare Blitz","Knock Off","Parting Shot"],"item":"Safety Goggles","ability":"Intimidate","stats":{"spe":91,"atk":183,"spa":90,"def":110,"spd":110}}],"bench":[]}}'::jsonb,
    'p1',
    'field_interaction',
    '{"type":"move","move":"Glacial Lance","target":"p2a"}'::jsonb,
    '[{"type":"move","move":"Follow Me","target":"p1b"},{"type":"move","move":"High Horsepower","target":"p2b"},{"type":"move","move":"Protect","target":"p1a"}]'::jsonb,
    '{"templateType":"field_interaction","fields":{"winner":"Glacial Lance","reason":"Under Trick Room Calyrex-Ice moves before faster opponents and spread pressure is the deterministic line."}}'::jsonb,
    3,
    ARRAY['field_interaction','trick_room','calyrex_ice'],
    'approved',
    now()
  ),
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'::uuid,
    'replay',
    'reg-h',
    '{"turn":10,"weather":null,"terrain":"Psychic Terrain","pseudoWeather":[],"p1":{"sideConditions":["Reflect"],"active":[{"species":"Farigiraf","level":50,"currentHp":192,"maxHp":192,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Trick Room","Psychic","Helping Hand","Protect"],"item":"Throat Spray","ability":"Armor Tail","stats":{"spe":80,"atk":90,"spa":178,"def":90,"spd":110}},{"species":"Ursaluna-Bloodmoon","level":50,"currentHp":219,"maxHp":219,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Blood Moon","Hyper Voice","Earth Power","Protect"],"item":"Life Orb","ability":"Mind''s Eye","stats":{"spe":52,"atk":90,"spa":205,"def":140,"spd":85}}],"bench":[]},"p2":{"sideConditions":[],"active":[{"species":"Kingambit","level":50,"currentHp":207,"maxHp":207,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Kowtow Cleave","Sucker Punch","Iron Head","Protect"],"item":"Black Glasses","ability":"Defiant","stats":{"spe":70,"atk":205,"spa":72,"def":140,"spd":105}},{"species":"Flutter Mane","level":50,"currentHp":80,"maxHp":131,"status":null,"statBoosts":{"atk":0,"def":0,"spa":0,"spd":0,"spe":0},"moves":["Moonblast","Shadow Ball","Protect","Icy Wind"],"item":"Focus Sash","ability":"Protosynthesis","stats":{"spe":205,"atk":67,"spa":205,"def":75,"spd":155}}],"bench":[]}}'::jsonb,
    'p1',
    'field_interaction',
    '{"type":"move","move":"Blood Moon","target":"p2b"}'::jsonb,
    '[{"type":"move","move":"Trick Room","target":"p1a"},{"type":"move","move":"Psychic","target":"p2a"},{"type":"move","move":"Hyper Voice","target":"p2a"}]'::jsonb,
    '{"templateType":"field_interaction","fields":{"winner":"Blood Moon","reason":"Psychic Terrain and Armor Tail block priority pressure, so Ursaluna can take the direct KO line."}}'::jsonb,
    3,
    ARRAY['field_interaction','priority_block','psychic_terrain'],
    'approved',
    now()
  )
)
INSERT INTO puzzles (
  id,
  source,
  format,
  game_state,
  player_side,
  question_type,
  correct_action,
  wrong_actions,
  explanation,
  difficulty,
  tags,
  status,
  approved_at
)
SELECT
  id,
  source,
  format,
  game_state,
  player_side,
  question_type,
  correct_action,
  wrong_actions,
  explanation,
  difficulty,
  tags,
  status,
  approved_at
FROM seed_puzzles
ON CONFLICT (id) DO NOTHING;
